import type {
  ComplaintData,
  DepotStat,
  NotificationLogItem,
  PublicTransparencyStats,
} from '../types';


export const MOCK_DEPOTS: DepotStat[] = [
  {
    code: 'KKD',
    name: 'Kozhikode Depot',
    nameMl: 'കോഴിക്കോട് ഡിപ്പോ',
    zone: 'Northern Zone',
    totalComplaints: 142,
    openComplaints: 14,
    resolvedComplaints: 122,
    slaBreaches: 6,
    averageResolutionHours: 11.4,
  },
  {
    code: 'GVR',
    name: 'Guruvayur Depot',
    nameMl: 'ഗുരുവായൂർ ഡിപ്പോ',
    zone: 'Central Zone',
    totalComplaints: 98,
    openComplaints: 9,
    resolvedComplaints: 86,
    slaBreaches: 3,
    averageResolutionHours: 9.8,
  },
  {
    code: 'TVM',
    name: 'Thiruvananthapuram Central',
    nameMl: 'തിരുവനന്തപുരം സെൻട്രൽ',
    zone: 'South Zone',
    totalComplaints: 215,
    openComplaints: 28,
    resolvedComplaints: 181,
    slaBreaches: 9,
    averageResolutionHours: 14.2,
  },
  {
    code: 'EKM',
    name: 'Ernakulam Depot',
    nameMl: 'എറണാകുളം ഡിപ്പോ',
    zone: 'Central Zone',
    totalComplaints: 187,
    openComplaints: 22,
    resolvedComplaints: 157,
    slaBreaches: 8,
    averageResolutionHours: 13.1,
  },
  {
    code: 'TCR',
    name: 'Thrissur Depot',
    nameMl: 'തൃശ്ശൂർ ഡിപ്പോ',
    zone: 'Central Zone',
    totalComplaints: 124,
    openComplaints: 11,
    resolvedComplaints: 110,
    slaBreaches: 4,
    averageResolutionHours: 10.5,
  },
  {
    code: 'PKD',
    name: 'Palakkad Depot',
    nameMl: 'പാലക്കാട് ഡിപ്പോ',
    zone: 'Northern Zone',
    totalComplaints: 103,
    openComplaints: 12,
    resolvedComplaints: 88,
    slaBreaches: 3,
    averageResolutionHours: 12.0,
  },
];

export const INITIAL_COMPLAINTS: ComplaintData[] = [
  {
    id: 'c-101',
    referenceNumber: 'SAM-2026-001284',
    createdAt: '2026-09-23T14:30:00Z',
    category: 'cleanliness',
    route: {
      origin: 'Guruvayur',
      destination: 'Kozhikode',
      via: 'Ponnani - Tirur',
    },
    busNumber: 'KL-15-A-4892',
    location: 'Inside passenger cabin, middle row seats',
    description:
      'The seats in the 4th and 5th row had discarded snack wrappers and sticky beverage spills. Cleanliness at the origin depot was evidently skipped.',
    audioTranscript:
      'I have a cleanliness complaint about the bus travelling from Guruvayur to Kozhikode. The seats in the middle row are very dirty and unhygienic.',
    status: 'in_progress',
    assignedDepot: {
      code: 'KKD',
      name: 'Kozhikode Depot',
      nameMl: 'കോഴിക്കോട് ഡിപ്പോ',
      zone: 'Northern Zone',
      officerInCharge: 'K. R. Sivadasan (Assistant Depot Engineer)',
    },
    slaTargetHours: 24,
    slaBreachTime: '2026-09-24T14:30:00Z',
    timeline: [
      {
        id: 't-1',
        status: 'submitted',
        title: 'Grievance Registered',
        titleMl: 'പരാതി സമർപ്പിച്ചു',
        description: 'Passenger grievance recorded via voice and verified by complainant.',
        descriptionMl: 'യാത്രക്കാരന്റെ ശബ്ദസന്ദേശം വഴി പരാതി രേഖപ്പെടുത്തി ഉറപ്പുവരുത്തി.',
        timestamp: '2026-09-23 14:30',
        actor: 'Passenger (Anonymized)',
      },
      {
        id: 't-2',
        status: 'assigned',
        title: 'Assigned to Operating Depot',
        titleMl: 'ഓപ്പറേറ്റിംഗ് ഡിപ്പോയ്ക്ക് കൈമാറി',
        description: 'Mapped to Kozhikode Depot via official route schedule #GVR-KKD-EXP-08.',
        descriptionMl: 'ഔദ്യോഗിക റൂട്ട് മാപ്പിംഗ് പ്രകാരം കോഴിക്കോട് ഡിപ്പോയിലേക്ക് കൈമാറി.',
        timestamp: '2026-09-23 14:32',
        actor: 'SAMADHAN Automated Route Engine',
      },
      {
        id: 't-3',
        status: 'acknowledged',
        title: 'Acknowledged by Depot Officer',
        titleMl: 'ഡിപ്പോ ഓഫീസർ പരിശോധിച്ച് സ്വീകരിച്ചു',
        description: 'Assigned to Maintenance Bay 2 cleaning roster upon termination at Kozhikode stand.',
        descriptionMl: 'കോഴിക്കോട് സ്റ്റാൻഡിൽ എത്തുമ്പോൾ വാഹനം ശുചീകരിക്കാൻ നിർദ്ദേശം നൽകി.',
        timestamp: '2026-09-23 15:10',
        actor: 'K. R. Sivadasan (Depot Engineer)',
      },
      {
        id: 't-4',
        status: 'in_progress',
        title: 'Deep Cleaning in Progress',
        titleMl: 'ശുചീകരണ പ്രക്രിയ നടക്കുന്നു',
        description: 'Vehicle berthed at Kozhikode yard for sanitize cycle before next departure.',
        descriptionMl: 'അടുത്ത ട്രിപ്പിന് മുൻപായി വാഹനം ശുചീകരണത്തിന് കയറ്റി.',
        timestamp: '2026-09-23 17:45',
        actor: 'Kozhikode Depot Yard Supervisor',
      },
    ],
    passengerContact: {
      preferredChannel: 'whatsapp',
      anonymizedTarget: 'ANON-USR-421',
    },
  },
  {
    id: 'c-102',
    referenceNumber: 'SAM-2026-000982',
    createdAt: '2026-09-21T08:15:00Z',
    category: 'delay_schedule',
    route: {
      origin: 'Palakkad',
      destination: 'Thrissur',
      via: 'Alathur - Vadakkencherry',
    },
    busNumber: 'KL-15-A-3120',
    location: 'Palakkad KSRTC Stand Bay 4',
    description:
      'Superfast service scheduled for 08:00 AM did not turn up. No announcement or replacement crew arranged for over 1 hour.',
    status: 'escalated',
    assignedDepot: {
      code: 'PKD',
      name: 'Palakkad Depot',
      nameMl: 'പാലക്കാട് ഡിപ്പോ',
      zone: 'Northern Zone',
      officerInCharge: 'M. Chandran (Station Master)',
    },
    slaTargetHours: 18,
    slaBreachTime: '2026-09-22T02:15:00Z',
    isEscalated: true,
    escalatedTo: 'District Transport Officer (DTO) - Palakkad',
    timeline: [
      {
        id: 't-201',
        status: 'submitted',
        title: 'Grievance Registered',
        titleMl: 'പരാതി സമർപ്പിച്ചു',
        description: 'Passenger grievance recorded.',
        timestamp: '2026-09-21 08:15',
        actor: 'Passenger',
      },
      {
        id: 't-202',
        status: 'assigned',
        title: 'Assigned to Palakkad Depot',
        titleMl: 'പാലക്കാട് ഡിപ്പോയിലേക്ക് കൈമാറി',
        description: 'Route originating depot assigned for schedule non-compliance review.',
        timestamp: '2026-09-21 08:18',
        actor: 'Route Engine',
      },
      {
        id: 't-203',
        status: 'sla_breached',
        title: 'SLA Limit Exceeded (18h)',
        titleMl: 'നിശ്ചിത സമയപരിധി ലംഘിച്ചു (18 മണിക്കൂർ)',
        description: 'No resolution or official response received from depot within 18 hours.',
        timestamp: '2026-09-22 02:15',
        actor: 'System SLA Monitor',
        isBreached: true,
      },
      {
        id: 't-204',
        status: 'escalated',
        title: 'Auto-Escalated to Tier 2 (DTO)',
        titleMl: 'ജില്ലാ ട്രാൻസ്പോർട്ട് ഓഫീസർക്ക് (DTO) കൈമാറി',
        description: 'Incident escalated to District Transport Officer for inquiry and explanation.',
        timestamp: '2026-09-22 02:16',
        actor: 'Automated Escalation Rule #ESC-T2',
      },
    ],
    passengerContact: {
      preferredChannel: 'sms',
      anonymizedTarget: 'ANON-USR-910',
    },

  },
  {
    id: 'c-103',
    referenceNumber: 'SAM-2026-000845',
    createdAt: '2026-09-20T11:00:00Z',
    category: 'safety',
    route: {
      origin: 'Thiruvananthapuram',
      destination: 'Ernakulam',
      via: 'Kollam - Alappuzha',
    },
    busNumber: 'KL-15-A-7011',
    location: 'Near Karunagappally bypass',
    description:
      'Driver was continuously using mobile phone while driving on wet rain highway. Overtook dangerously on narrow curves.',
    status: 'resolved',
    assignedDepot: {
      code: 'TVM',
      name: 'Thiruvananthapuram Central',
      nameMl: 'തിരുവനന്തപുരം സെൻട്രൽ',
      zone: 'South Zone',
      officerInCharge: 'R. Binu (Enforcement Inspector)',
    },
    slaTargetHours: 6,
    timeline: [
      {
        id: 't-301',
        status: 'submitted',
        title: 'High Priority Safety Complaint',
        timestamp: '2026-09-20 11:00',
      },
      {
        id: 't-302',
        status: 'assigned',
        title: 'Routed to Vigilance & TVM Depot',
        timestamp: '2026-09-20 11:02',
      },
      {
        id: 't-303',
        status: 'in_progress',
        title: 'Crew Summoned & Dashcam Checked',
        timestamp: '2026-09-20 12:40',
      },
      {
        id: 't-304',
        status: 'resolved',
        title: 'Action Taken & Crew Censured',
        titleMl: 'നടപടി സ്വീകരിച്ചു',
        description:
          'Driver was called in by Safety Enforcement Cell. Driver de-rostered for 7 days pending mandatory defensive driving refresher.',
        timestamp: '2026-09-20 15:30',
        actor: 'Enforcement Wing TVM',
      },
    ],
    passengerContact: {
      preferredChannel: 'whatsapp',
      anonymizedTarget: 'ANON-USR-188',
    },
  },
  {
    id: 'c-104',
    referenceNumber: 'SAM-2026-001390',
    createdAt: '2026-09-23T19:10:00Z',
    category: 'staff_behaviour',
    route: {
      origin: 'Kottayam',
      destination: 'Kumily',
      via: 'Kanjirappally - Mundakkayam',
    },
    busNumber: 'KL-15-A-5521',
    location: 'Mundakkayam stop',
    description:
      'Conductor refused student concession card without looking at valid expiry date and used harsh language in front of passengers.',
    status: 'assigned',
    assignedDepot: {
      code: 'KTM',
      name: 'Kottayam Depot',
      nameMl: 'കോട്ടയം ഡിപ്പോ',
      zone: 'Central Zone',
      officerInCharge: 'P. Manoj (Station Inspector)',
    },
    slaTargetHours: 18,
    timeline: [
      {
        id: 't-401',
        status: 'submitted',
        title: 'Grievance Registered',
        timestamp: '2026-09-23 19:10',
      },
      {
        id: 't-402',
        status: 'assigned',
        title: 'Assigned to Kottayam Depot',
        timestamp: '2026-09-23 19:12',
        description: 'Under review by Kottayam Grievance Cell.',
      },
    ],
    passengerContact: {
      preferredChannel: 'whatsapp',
      anonymizedTarget: 'ANON-USR-334',
    },
  },
  {
    id: 'c-105',
    referenceNumber: 'SAM-2026-001402',
    createdAt: '2026-09-23T19:55:00Z',
    category: 'bus_condition',
    route: {
      origin: 'Kannur',
      destination: 'Mananthavady',
      via: 'Mattannur - Nedumpoil',
    },
    busNumber: 'KL-15-A-1190',
    location: 'Ghat section near Nedumpoil',
    description:
      'Window glass shutter was stuck open during heavy rainfall, drenching passengers seated on the right side.',
    status: 'submitted',
    slaTargetHours: 36,
    timeline: [
      {
        id: 't-501',
        status: 'submitted',
        title: 'Voice Complaint Submitted',
        timestamp: '2026-09-23 19:55',
        description: 'Pending automated route schedule verification.',
      },
    ],
    passengerContact: {
      preferredChannel: 'sms',
      anonymizedTarget: 'ANON-USR-801',
    },
  },
];

export const MOCK_NOTIFICATIONS: NotificationLogItem[] = [
  {
    id: 'n-1',
    complaintRef: 'SAM-2026-001284',
    channel: 'whatsapp',
    recipientAnonymized: 'ANON-USR-421',
    eventType: 'registered',
    subject: 'Samadhan Grievance Registered',
    messageContent:
      'Grievance regarding Guruvayur → Kozhikode (Cleanliness) registered. Reference: SAM-2026-001284. Track at /track?ref=SAM-2026-001284',
    status: 'read',
    timestamp: '2026-09-23 14:31',
  },
  {
    id: 'n-2',
    complaintRef: 'SAM-2026-001284',
    channel: 'whatsapp',
    recipientAnonymized: 'ANON-USR-421',
    eventType: 'assigned',
    subject: 'Assigned to Operating Depot',
    messageContent:
      'Update: Complaint SAM-2026-001284 mapped to Kozhikode Depot. Targeted resolution within 24 hours under Citizen Charter SLA.',
    status: 'delivered',
    timestamp: '2026-09-23 14:33',
  },
  {
    id: 'n-3',
    complaintRef: 'SAM-2026-000982',
    channel: 'sms',
    recipientAnonymized: 'ANON-USR-910',
    eventType: 'escalated',
    subject: 'Escalation Notice - Tier 2',
    messageContent:
      'SAMADHAN Alert: Grievance SAM-2026-000982 exceeded 18h depot SLA and auto-escalated to District Transport Officer (DTO) Palakkad.',
    status: 'delivered',
    timestamp: '2026-09-22 02:17',
  },
  {
    id: 'n-4',
    complaintRef: 'SAM-2026-000845',
    channel: 'whatsapp',
    recipientAnonymized: 'ANON-USR-188',
    eventType: 'resolved',
    subject: 'Complaint Resolved',
    messageContent:
      'Complaint SAM-2026-000845 has been investigated and resolved by Thiruvananthapuram Vigilance. Corrective action documented.',
    status: 'read',
    timestamp: '2026-09-20 15:32',
  },
  {
    id: 'n-5',
    complaintRef: 'SAM-2026-001402',
    channel: 'sms',
    recipientAnonymized: 'ANON-USR-801',
    eventType: 'registered',
    subject: 'Registration Confirmation',
    messageContent:
      'Grievance SAM-2026-001402 registered for Kannur - Mananthavady bus condition. Track updates anytime on Samadhan.',
    status: 'sent',
    timestamp: '2026-09-23 19:56',
  },
];


export const MOCK_PUBLIC_STATS: PublicTransparencyStats = {
  totalRegistered30Days: 1482,
  resolutionRatePercent: 91.4,
  avgResolutionTimeHours: 11.8,
  activeEscalationRatePercent: 4.2,
  categoryBreakdown: [
    { category: 'cleanliness', count: 372, percentage: 25.1 },
    { category: 'delay_schedule', count: 326, percentage: 22.0 },
    { category: 'staff_behaviour', count: 248, percentage: 16.7 },
    { category: 'bus_condition', count: 215, percentage: 14.5 },
    { category: 'driver_conductor', count: 148, percentage: 10.0 },
    { category: 'safety', count: 89, percentage: 6.0 },
    { category: 'ticketing', count: 54, percentage: 3.6 },
    { category: 'accessibility', count: 30, percentage: 2.1 },
  ],
  depotBreakdown: [
    { depotName: 'Kozhikode', resolved: 122, open: 14 },
    { depotName: 'Thiruvananthapuram', resolved: 181, open: 28 },
    { depotName: 'Ernakulam', resolved: 157, open: 22 },
    { depotName: 'Thrissur', resolved: 110, open: 11 },
    { depotName: 'Guruvayur', resolved: 86, open: 9 },
    { depotName: 'Palakkad', resolved: 88, open: 12 },
  ],
  monthlyTrend: [
    { month: 'Apr', received: 1120, resolved: 1040 },
    { month: 'May', received: 1250, resolved: 1180 },
    { month: 'Jun', received: 1390, resolved: 1290 },
    { month: 'Jul', received: 1420, resolved: 1310 },
    { month: 'Aug', received: 1510, resolved: 1395 },
    { month: 'Sep (MTD)', received: 1482, resolved: 1354 },
  ],
};
